apiVersion: v1
kind: Service
metadata:
  labels:
    test: project
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.spec.ports.port }}
    targetPort: {{ .Values.spec.ports.targetPort }}
    protocol: {{ .Values.spec.ports.protocol }}
  selector:
    test: project
  type: {{ .Values.spec.type }}