apiVersion: v1
kind: Service
metadata:
  labels:
    test: project
  name: techtrends
  namespace: sandbox
spec:
  ports:
  - port: 4111
    targetPort: 3111
    protocol: TCP
  selector:
    test: project
  type: ClusterIP