namespace:
  name: staging
service:
  port: 5111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP
image:
  repository: nikekin321/techtrends
  tag: latest
  imagePullPolicy: Always
resources:
  requests:
    memory: 90Mi
    cpu: 300m
  limits:
    memory: 128Mi
    cpu: 500m
livenessprobepath: /healthz
readinessprobepath: /healthz
containerPort: 3111
replicaCount:3
