namespace:
  name: sandbox
service:
  port: 4111
  targetPort: 3111
  protcol: TCP
  type: ClusterIP
image:
  repository: nikekin321/techtrends
  tag: latest
  imagePullPolicy: IfNotPresent
resources:
  requests:
    memory: 64Mi
    cpu: 260m
  limits:
    memory: 128Mi
    cpu: 500m
livenessprobepath: /healthz
readinessprobepath: /healthz
containerPort: 3111
replicaCount: 1
